# Generated by Django 6.0.6 on 2026-06-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Referencia do arquivo, ex.: PT-ADVIS-AC-GCVIS-H-D-001-01016_m0003",
                        max_length=200,
                        unique=True,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="titulo"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="manuscripts/", verbose_name="imagem"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Arquivo ou coleccao de origem.",
                        max_length=200,
                        verbose_name="fonte",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, verbose_name="URL de origem"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "manuscrito",
                "verbose_name_plural": "manuscritos",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="transcricao")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("review", "Em revisao"),
                            ("approved", "Aprovada"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="notas do transcritor"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcriptions",
                        to="manuscripts.manuscript",
                        verbose_name="manuscrito",
                    ),
                ),
                (
                    "transcriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="transcritor",
                    ),
                ),
            ],
            options={
                "verbose_name": "transcricao",
                "verbose_name_plural": "transcricoes",
                "ordering": ["-updated_at"],
            },
        ),
    ]
