# Generated by Django 6.0.6 on 2026-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscripts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manuscript",
            options={
                "ordering": ["reference_code", "image_no"],
                "verbose_name": "manuscrito",
                "verbose_name_plural": "manuscritos",
            },
        ),
        migrations.AddField(
            model_name="manuscript",
            name="image_no",
            field=models.CharField(
                blank=True,
                help_text="Ex.: m0003",
                max_length=50,
                verbose_name="numero da imagem",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="image_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash dos bytes da imagem original (deduplicacao/correspondencia).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="SHA-256 da imagem",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="metadata_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("filename", "Nome do ficheiro"),
                    ("scraped", "Recolhido (scrape)"),
                    ("digitarq", "DigitARQ"),
                ],
                default="manual",
                max_length=20,
                verbose_name="proveniencia dos metadados",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="raw_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="metadados originais"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="reference_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Codigo ISAD da unidade/livro, sem o numero de imagem.",
                max_length=255,
                verbose_name="codigo de referencia (unidade)",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Confirmado por um especialista; importacoes nao sobrescrevem.",
                verbose_name="verificado",
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="manuscripts/", verbose_name="imagem"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Referencia completa por imagem, ex.: PT-ADVIS-...-01016_m0003",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="referencia",
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="titulo"),
        ),
    ]
